platform :ios, "9.0"
inhibit_all_warnings!

target 'GX' do
    pod "AFNetworking"
    pod "ZLPhotoBrowser"
    pod "MJRefresh"
    pod "zhPopupController"
    pod "IQKeyboardManager"
    pod "NHHUDExtend"
    pod "JJFontFit"
    pod "YYCache"
    pod "YYModel"
    pod "YYText"
    pod "JXCategoryView"
    pod "ZLCollectionViewFlowLayout"
    pod "ZXEmptyView"
end